SET(FOS ${ARDUINO_GD32_FREERTOS}/FreeRTOS)

IF( "${LN_MCU}" STREQUAL "M3")
    SET(LN_FREERTOS_PORT ${FOS}/portable/GCC/ARM_CM3/  CACHE INTERNAL "")
ELSE()
    IF( "${LN_MCU}" STREQUAL "M4")
        SET(LN_FREERTOS_PORT ${FOS}/portable/GCC/ARM_CM4F/  CACHE INTERNAL "")
    ELSE()
        MESSAGE(FATAL_ERROR "Unsupported Arch for FreeRTOS ${MCU}")
    ENDIF()
ENDIF()



SET(LN_FREERTOS_PORT_SOURCES  ${LN_FREERTOS_PORT}/port.c )


