SET(FOS ${ARDUINO_GD32_FREERTOS}/FreeRTOS)
IF(1)
    SET(LN_FREERTOS_PORT ${ARDUINO_GD32_FREERTOS}/freeRTOS_extension/N200_nuclei )
    SET(N200  ${LN_FREERTOS_PORT}/port.c ${LN_FREERTOS_PORT}/portasm.S )
ELSE()
    SET(LN_FREERTOS_PORT ${ARDUINO_GD32_FREERTOS}/freeRTOS_extension/N200 )
    SET(N200  ${LN_FREERTOS_PORT}/port.c ${LN_FREERTOS_PORT}/portASM.S )
ENDIF()

