SET(FOS ${ARDUINO_GD32_FREERTOS}/FreeRTOS)
SET(LN_FREERTOS_PORT ${FOS}/portable/GCC/ARM_CM33_NTZ/non_secure/  CACHE INTERNAL "")
SET(LN_FREERTOS_PORT_SOURCES  ${LN_FREERTOS_PORT}/port.c ${LN_FREERTOS_PORT}/portasm.c)


