SET(CH32V3x_FOLDER ${LN_MCU_FOLDER}/tinyUsb/)
SET(DRIVERS             ${LNSRC}/lnTinyUsbImpl.cpp        ${LNSRC}/lnUsbStack.cpp ${LNSRC}/lnUsbLL.cpp)
SET(LN_OPT_TUSB_MCU     OPT_MCU_STM32F1)
SET(LN_OPT_MODE         OPT_MODE_FULL_SPEED)              
SET(LN_TUSB_EXTRA_DEF   "STM32F103xB=1")
