include_directories(${AF_FOLDER}/libraries/tinyUsb)
include_directories(${AF_FOLDER}/libraries/tinyUsb/src)
include_directories(${AF_FOLDER}/libraries/tinyUsb/src/src)
include_directories(${AF_FOLDER}/libraries/tinyUsb/src/src/common)
include_directories(${AF_FOLDER}/libraries/tinyUsb/src/src/device)
include_directories(${AF_FOLDER}/libraries/tinyUsb/src/src/class)
