# We ony enable usb for arm and non small footprint
IF(NOT DEFINED LN_ARCH)
  IF(USE_CH32V3x) # RISCV
    SET(LN_ENABLED_BOARDS CH32F1 RP2040 RP2350 STM32F1  NRF51 NRF91 LPC11XX LPC15XX LPC17XX STM32F4 STM32G0 STM32H7 STM32H5   STM32L4 CACHE INTERNAL "")
    # try without crystal...
    #SET(LN_USE_INTERNAL_CLOCK True        CACHE INTERNAL "")
    #SET(LN_MCU_SPEED          48000000    CACHE INTERNAL "") # 96 Mhz
    #SET(LN_MCU_SPEED          96000000    CACHE INTERNAL "") # 96 Mhz
    SET(LN_MCU_SPEED          144000000    CACHE INTERNAL "") # 144 Mhz

    SET(LN_ARCH "RISCV"                   CACHE INTERNAL "")
    SET(LN_MCU  "CH32V3x"                 CACHE INTERNAL "")
    SET(LN_MCU_RAM_SIZE       64          CACHE INTERNAL "")
    SET(LN_MCU_FLASH_SIZE     256         CACHE INTERNAL "")
    SET(LN_MCU_STATIC_RAM     10           CACHE INTERNAL "")
    SET(LN_SPEC               "picolibc"  CACHE INTERNAL "") # if not set we use nano
    SET(LN_BOOTLOADER_SIZE     0          CACHE INTERNAL "")
    #SET(LN_SPEC         "picolibc"   CACHE INTERNAL "") # if not set we use nano
  ELSE()
    IF(USE_GD32F3)
      SET(LN_ENABLED_BOARDS CH32F1 RP2040 RP2350 STM32F1  NRF51 NRF91 LPC11XX LPC15XX LPC17XX STM32F4 STM32G0 STM32H7 STM32H5   STM32L4 CACHE INTERNAL "")
      SET(LN_ARCH            "ARM" CACHE INTERNAL "")
      SET(LN_MCU             "M4"  CACHE INTERNAL "")
      SET(LN_MCU_FLASH_SIZE  256   CACHE INTERNAL "")
      SET(LN_MCU_RAM_SIZE    46    CACHE INTERNAL "")
      SET(LN_MCU_STATIC_RAM  8     CACHE INTERNAL "")
      #SET(LN_MCU_SPEED 72000000    CACHE INTERNAL "") #=> ok
      SET(LN_MCU_SPEED 96000000    CACHE INTERNAL "") #=> ok

      #      SET(LN_MCU_SPEED  72000000    CACHE INTERNAL "") #=> ok
      SET(LN_SPEC         "picolibc"   CACHE INTERNAL "") # if not set we use nano
      SET(LN_BOOTLOADER_SIZE 0     CACHE INTERNAL "")
    ELSEIF(USE_RP2040 )
      SET(LN_ENABLED_BOARDS CH32F1 RP2040 RP2350 STM32F1  NRF51 NRF91 LPC11XX LPC15XX LPC17XX STM32F4 STM32G0 STM32H7 STM32H5   STM32L4 CACHE INTERNAL "")
      SET(LN_ARCH            "ARM" CACHE INTERNAL "")
      SET(LN_MCU             "RP2040"  CACHE INTERNAL "")
      IF(USE_RP2040_PURE_RAM )
        SET(LN_MCU_FLASH_SIZE  128   CACHE INTERNAL "")
        SET(LN_MCU_RAM_SIZE    64    CACHE INTERNAL "")
      ELSE()
        SET(LN_MCU_RAM_SIZE    200    CACHE INTERNAL "")
        SET(LN_MCU_FLASH_SIZE  2048   CACHE INTERNAL "")
      ENDIF()
      SET(LN_MCU_SPEED       125000000       CACHE INTERNAL "")
      SET(LN_MCU_STATIC_RAM  10     CACHE INTERNAL "")
      SET(LN_MCU_EEPROM_SIZE 2     CACHE INTERNAL "")
      SET(LN_BOOTLOADER_SIZE 0     CACHE INTERNAL "")
      SET(LN_SPEC            "picolibc"   CACHE INTERNAL "") # if not set we use nano

    ELSEIF(USE_RP2350)
      SET(LN_ENABLED_BOARDS CH32F1 RP2040 RP2350 STM32F1  NRF51 NRF91 LPC11XX LPC15XX LPC17XX STM32F4 STM32G0 STM32H7 STM32H5   STM32L4 CACHE INTERNAL "")
      SET(LN_ARCH            "ARM" CACHE INTERNAL "")
      SET(LN_MCU             "RP2350"  CACHE INTERNAL "")
      IF(USE_RP2350_PURE_RAM)
        SET(LN_MCU_FLASH_SIZE  256   CACHE INTERNAL "")
        SET(LN_MCU_RAM_SIZE    256    CACHE INTERNAL "")
      ELSE()
        SET(LN_MCU_RAM_SIZE    512    CACHE INTERNAL "")
        SET(LN_MCU_FLASH_SIZE  2048   CACHE INTERNAL "")
      ENDIF()
      SET(LN_MCU_SPEED       150000000       CACHE INTERNAL "")
      SET(LN_MCU_STATIC_RAM  10     CACHE INTERNAL "")
      SET(LN_MCU_EEPROM_SIZE 2     CACHE INTERNAL "")
      SET(LN_BOOTLOADER_SIZE 0     CACHE INTERNAL "")
      SET(LN_SPEC            "picolibc"   CACHE INTERNAL "") # if not set we use nano

    ELSE() # Small bluepill style
      SET(LN_ARCH            "ARM" CACHE INTERNAL "")
      SET(LN_MCU             "M3"  CACHE INTERNAL "")
      SET(LN_MCU_RAM_SIZE    20    CACHE INTERNAL "")
      SET(LN_MCU_SPEED 72000000       CACHE INTERNAL "")
      SET(LN_ENABLED_BOARDS   CH32F1 RP2040 RP2350 STM32F1 CACHE INTERNAL "")
      IF(USE_SMALLFOOTPRINT)
        SET(LN_MCU_STATIC_RAM  3    CACHE INTERNAL "")
        SET(LN_MCU_FLASH_SIZE  64   CACHE INTERNAL "")
        SET(LN_MCU_EEPROM_SIZE 2    CACHE INTERNAL "")
      ELSE() # "Big" flash
        SET(LN_MCU_STATIC_RAM  7     CACHE INTERNAL "")
        SET(LN_MCU_FLASH_SIZE  188   CACHE INTERNAL "")
        SET(LN_MCU_EEPROM_SIZE 2     CACHE INTERNAL "")
        SET(LN_BOOTLOADER_SIZE 0     CACHE INTERNAL "")
      ENDIF()
      SET(LN_SPEC         "picolibc"   CACHE INTERNAL "") # if not set we use nano
    ENDIF() # GD32F3
  ENDIF() # CH32V3
ENDIF(NOT DEFINED LN_ARCH)
MESSAGE(STATUS "Architecture ${LN_ARCH}, MCU=${LN_MCU}")
