CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

SET(ESPRIT_ROOT  ${CMAKE_SOURCE_DIR}/esprit/)
find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
  set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_FOUND})
  set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_FOUND})
endif()
INCLUDE(common_platformConfig)
INCLUDE(common_mcuSelect)
SET(CMAKE_TOOLCHAIN_FILE ${ESPRIT_ROOT}/esprit.cmake)
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake ${ESPRIT_ROOT}/cmake CACHE INTERNAL "")
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)



