// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //
#include "lnGPIO.h"
#include "ln_rp_pio.h"
#include "stdint.h"

#define blink_wrap_target 2
#define blink_wrap 7

static const uint16_t blink_program_instructions[] = {
    0x80a0, //  0: pull   block
    0x6040, //  1: out    y, 32
            //     .wrap_target
    0xa022, //  2: mov    x, y
    0xe001, //  3: set    pins, 1
    0x0044, //  4: jmp    x--, 4
    0xa022, //  5: mov    x, y
    0xe000, //  6: set    pins, 0
    0x0047, //  7: jmp    x--, 7
            //     .wrap
};

void runPio()
{
    lnPin pin = LN_SYSTEM_LED;
    rpPIO xpio(0);
    rpPIO_SM *xsm = xpio.getSm(0);

    lnPinModePIO(pin, 0);

    rpPIO_pinConfig pinConfig;
    pinConfig.sets.pinNb = 1;
    pinConfig.sets.startPin = LN_SYSTEM_LED;

    xsm->uploadCode(8, blink_program_instructions, blink_wrap_target, blink_wrap);
    xsm->configure(pinConfig); //<<<=========
    xsm->execute();

    uint32_t wait = (lnPeripherals::getClock(pSYSCLOCK) / (4 * 2)) - 3;
    xsm->write(1, &wait);

    while (1)
    {
        xDelay(5000);
    }
}

//--
