#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    #[link_name = "\u{1}_Z10LoggerInitv"]
    pub fn LoggerInit();
}
unsafe extern "C" {
    #[link_name = "\u{1}_Z11debugLoggerPKcz"]
    pub fn debugLogger(fmt: *const cty::c_char, ...);
}
unsafe extern "C" {
    pub fn Logger(fmt: *const cty::c_char, ...);
}
unsafe extern "C" {
    pub fn Logger_C(fmt: *const cty::c_char, ...) -> cty::c_int;
}
unsafe extern "C" {
    pub fn Logger_chars(n: cty::c_int, data: *const cty::c_char);
}
pub type lnLoggerFunction =
    ::core::option::Option<unsafe extern "C" fn(n: cty::c_int, data: *const cty::c_char)>;
unsafe extern "C" {
    pub fn setLogger(f: lnLoggerFunction);
}
