
IF(0)
    SET(LN_ARCH "ARM" CACHE INTERNAL "")
    SET(LN_MCU  "M3" CACHE INTERNAL "")
ELSE()
    SET(LN_ARCH "RISCV" CACHE INTERNAL "")
    SET(LN_MCU  "VF103" CACHE INTERNAL "")
ENDIF()
MESSAGE(STATUS "Architecture ${LN_ARCH}, MCU=${LN_MCU}")
