IF(WIN32)    
    SET(PLATFORM_TOOLCHAIN_SUFFIX ".exe")
ENDIF(WIN32)



SET(PLATFORM_PREFIX arm-none-eabi-)
SET(PLATFORM_C_FLAGS " ")
IF(WIN32)
  SET(PLATFORM_TOOLCHAIN_PATH  "/c/dev/arm83/bin")
ELSE()
  SET(PLATFORM_CLANG_PATH /arm/tools_llvm/bin)
  SET(PLATFORM_CLANG_VERSION "-18")
  SET(PLATFORM_TOOLCHAIN_PATH "/arm/113/bin") 
ENDIF()

